# Generated by Django 4.2 on 2023-05-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('image', models.ImageField(null=True, upload_to='articles')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('dui', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=250)),
                ('clave', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_cliente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_producto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_usuario', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoValoraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_valoracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='articles')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(max_length=100)),
                ('precio_producto', models.IntegerField()),
                ('imagen_producto', models.ImageField(null=True, upload_to='articles')),
                ('especificaciones_producto', models.CharField(max_length=100)),
                ('descuento', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.categoria')),
                ('id_estado_producto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='privado.estadoproducto')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(default='', max_length=150)),
                ('descripcion_tipo_usuario', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privado.estadovaloraciones')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privado.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.CharField(max_length=150)),
                ('alias_usuario', models.CharField(max_length=100)),
                ('clave_usuario', models.CharField(max_length=100)),
                ('id_estado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.estadousuario')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.tipousuario')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.usuario'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now=True, null=True)),
                ('direccion_pedido', models.CharField(max_length=200, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_pedido', models.IntegerField()),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privado.cliente')),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privado.estadopedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_producto', models.ImageField(null=True, upload_to='articles')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.estadocliente'),
        ),
    ]
