# Generated by Django 4.0 on 2023-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
    ]
