# Generated by Django 4.2 on 2023-04-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido_usuario', models.CharField(max_length=100)),
                ('correo_usuario', models.CharField(max_length=150)),
                ('alias_usuario', models.CharField(max_length=100)),
                ('clave_usuario', models.CharField(max_length=100)),
                ('id_estado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.estadousuario')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.tipousuario')),
            ],
        ),
    ]
