# Generated by Django 4.0 on 2023-05-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoraciones',
            name='id_pedido',
        ),
        migrations.AddField(
            model_name='valoraciones',
            name='id_producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='privado.producto'),
        ),
    ]
