# Generated by Django 4.0 on 2023-04-25 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_estado_producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='privado.estadoproducto'),
        ),
        migrations.AlterField(
            model_name='estadoproducto',
            name='estado_producto',
            field=models.CharField(max_length=150),
        ),
    ]
