# Generated by Django 4.0 on 2023-04-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_producto_id_estado_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoproducto',
            name='estado_producto',
            field=models.CharField(max_length=100),
        ),
    ]
