# Generated by Django 4.0 on 2023-04-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_alter_categoria_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
