# Generated by Django 4.2 on 2023-04-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_valoracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.estadovaloracion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.producto')),
            ],
        ),
    ]
