# Generated by Django 4.0 on 2023-05-29 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0002_remove_valoraciones_id_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoraciones',
            name='id_estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='privado.estadovaloraciones'),
        ),
    ]
