# Generated by Django 4.2 on 2023-04-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0003_estadovaloracion_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='id_pedido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='privado.pedido'),
        ),
    ]
