# Generated by Django 4.0 on 2023-04-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0003_categoria_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
    ]
