# Generated by Django 4.0 on 2023-04-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0003_alter_estadoproducto_estado_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now=True)),
                ('direccion_pedido', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('precio_pedido', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.cliente')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.estadopedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privado.producto')),
            ],
        ),
    ]
