# Generated by Django 4.0 on 2023-05-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0003_alter_valoraciones_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoraciones',
            name='id_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privado.estadovaloraciones'),
        ),
        migrations.AlterField(
            model_name='valoraciones',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='privado.producto'),
        ),
    ]
