# Generated by Django 4.0 on 2023-04-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0004_rename_name_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
    ]
