# Generated by Django 4.0 on 2023-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0005_alter_categoria_descripcion_alter_categoria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(null=True, upload_to='articles'),
        ),
    ]
